stages:
  - install
  - build
  - test

variables:
  GO_VERSION: "1.22.5"

before_script:
  - echo "Début du pipeline"

install_packages:
  stage: install
  image: golang:$GO_VERSION
  script:
    - go mod download
  artifacts:
    paths:
      - go.sum
      - go.mod

build_project:
  stage: build
  image: golang:$GO_VERSION
  script:
    - go build -o myapp
  artifacts:
    paths:
      - myapp

run_tests:
  stage: test
  image: golang:$GO_VERSION
  script:
    - go test ./...
  coverage: '/^coverage: \d+\.\d+%$/'

after_script:
  - echo "Pipeline terminé"

