variables:
  GO_VERSION: "1.22.5"  # Specify the Go version you are using

stages:
  - setup

setup_go_environment:
  stage: setup
  script:
    - echo "Setting up Go environment"
    - curl -LO "https://golang.org/dl/go${GO_VERSION}.linux-amd64.tar.gz"
    - sudo tar -C /usr/local -xzf "go${GO_VERSION}.linux-amd64.tar.gz"
    - export PATH=/usr/local/go/bin:$PATH
    - go version
