stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "Étape de construction du projet"

test_job:
  stage: test
  script:
    - echo "Étape de tests du projet"

deploy_job:
  stage: deploy
  script:
    - echo "Étape de déploiement du projet"
