stages:
  - checkout

# Checkout stage
checkout:
  stage: checkout
  script:
    - git rev-parse --short HEAD > commit_hash.txt
    - export COMMIT_ID=$(cat commit_hash.txt)
    - export ZIP_FILE_NAME="${ARTIFACT_ID}-${COMMIT_ID}.zip"
    - echo "Commit Hash: ${COMMIT_ID}"
    - echo "Zip File Name: ${ZIP_FILE_NAME}"

